### ISSUE TITLE
moonraker-telegram-bot version cannot be parsed by Moonraker

### ISSUE THREAD

**Issue by JWRu** [nlef/moonraker-telegram-bot#253] opened 2023-02-06 17:06 UTC
### What happened and in what context?

The Moonraker Update Manager will show "? UNKNOWN" after an update to version v1.5-0-gb9b4700.
According to the Moonraker specialists the moonraker-telegram-bot dev tagged the latest release with a version that Moonraker can't parse.  The tags have to be compatible with the semantic version standard. 
https://semver.org/
<img width="928" alt="Bildschirm­foto 2023-02-06 um 11 07 25" src="https://user-images.githubusercontent.com/89386880/217037043-3601cc8c-64d8-4d5e-bc16-748d8620ddd7.png">

### What branch does this occur on?

development

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

**Comment by JWRu** [comment] 2023-02-06 17:12
I think it's just a typo. "v1.5-0..." should be changed to ""v1.5.0...".

**Comment by aka13-404** [comment] 2023-02-06 17:38
Thank you for being so quick!

To be honest, I am not sure where the -0 is coming from, the release is v1.5, but it seems that for semver it should be `v1.5.0`. I have corrected it, I'd appreciate if you can tell if its alright now.

**Comment by JWRu** [comment] 2023-02-06 18:55
The indication in Moonraker Update Manager didn't change. I tried a manual git pull but got the message that the package is already up to date.

**Comment by aka13-404** [comment] 2023-02-06 19:21
Well, you now how to wait, or delete everything and redownload. I hope it don't bothers you too much :(.
But we propably will have fixes very soon, when people will start using new features, and will roll over to 1.5.1 pretty fast, if that helps your bother

**Comment by Arksine** [comment] 2023-02-07 15:34
FWIW, the `-0` is generated by `git describe` and indicates the number of commits since the tag. 

I decided to relax the tag requirement in a new commit to Mooraker.  The tag can have fewer than 3 parts, so Moonraker will parse `v1.5`.  Anyone with a tag of `v1.5` should be able to update Moonraker, refresh available updates, then update `moonraker-telegram-bot`.

The only thing to keep in mind going forward is that a tag cannot have more than 3 parts, so for example a tag of `v1.5.0.1` will likely cause an issue.

**Comment by JWRu** [comment] 2023-02-07 17:41
The Moonraker update did the job. Everything is "UP-TO-DATE" now. Many thanks.

**Comment by aka13-404** [comment] 2023-02-07 19:10
> FWIW, the `-0` is generated by `git describe` and indicates the number of commits since the tag.
> 
> I decided to relax the tag requirement in a new commit to Mooraker. The tag can have fewer than 3 parts, so Moonraker will parse `v1.5`. Anyone with a tag of `v1.5` should be able to update Moonraker, refresh available updates, then update `moonraker-telegram-bot`.
> 
> The only thing to keep in mind going forward is that a tag cannot have more than 3 parts, so for example a tag of `v1.5.0.1` will likely cause an issue.
  
You are a magician, aprreciate it. Now I have one less place to make mistakes :D
Closing this then.

**Closed by aka13-404** 2023-02-07 19:10 UTC
Labels: bug, Next release

**Comment by cpasoft** [comment] 2023-07-29 10:34
I have this problem. I have updated Moonraker. Here is a screenshot of my versions.
I have already tried a complete uninstall and reinstall. I think this was after a recent moonraker update.
![imagen](https://github.com/nlef/moonraker-telegram-bot/assets/29692062/7a482432-9931-4056-bdb2-702f8b00e9b9)

**Comment by cpasoft** [comment] 2023-07-29 10:36
Note:

**Comment by cpasoft** [comment] 2023-07-29 10:37
Note:
Kiauh is detecting well BTW
![imagen](https://github.com/nlef/moonraker-telegram-bot/assets/29692062/abba8fda-b251-431c-aa17-9056d674a5ad)

**Comment by cpasoft** [comment] 2023-07-31 06:44
Is there a way to reopen this??... Or I must to create a new one...

**Comment by Arksine** [comment] 2023-07-31 11:27
It looks like this could be a regression in Mainsail.

Version 2.6.0:
![image](https://github.com/nlef/moonraker-telegram-bot/assets/9563098/8d92f66a-0321-4da0-8625-8929ac1e298a)

Version 2.6.2 (also seems to occur on 2.6.1)
![image](https://github.com/nlef/moonraker-telegram-bot/assets/9563098/893c6fd6-8a04-4b9b-98b8-68563bcf9ea1)

Its possible that Mainsail introduced its own tag validation.

**Comment by bigsubgit** [comment] 2024-01-10 16:23
Hello everyone, is it solved this? I've "unknown" yet.
